Make repo subrepoable
Unity-Technologies/graph-visualizer pull request #8
Opened 2018-02-02 23:13 UTC by amirebrahimi

I moved the files to the root and updated the README with instructions on how to clone directly into a project. This is what we did for [EditorVR](https://github.com/Unity-Technologies/EditorVR/) and [AutoLOD](https://github.com/Unity-Technologies/AutoLOD). I'm looking to make use of the graph visualizer for another project, but will need to subrepo it, so I figured I'd offer this back.

2018-02-06 15:40 UTC, romainf-unity commented
Hmm it's a bit of a problem since I moved them into a specific directory a few months ago: 5aa9fa8fbc261c2278bfbdfac90b19dc3481d6d9

I'll have to check with the Package team as well, I know I want to make this a package, but I don't know don't know what should be the directory pattern for that.

2018-02-06 15:41 UTC, romainf-unity commented
Also, instead of moving all the files, it's possible to do a sparse checkout:
https://stackoverflow.com/questions/600079/how-do-i-clone-a-subdirectory-only-of-a-git-repository#13738951

2018-02-06 17:42 UTC, amirebrahimi commented
Unfortunately sparse checkouts wouldn't be maintained for subrepos. The problem isn't with what directories get checked out, but instead from the need to check out at the root, which precludes a larger Unity project from being version controlled.

If you need to have a separate folder structure for packages, then a good solution is to have a separate repo that subrepos this one (or vice versa) and imports it at a specific location (i.e. if graph-visualizer is subrepo, then graph-visualizer-project would import it at Assets/GraphVisualizer). You'd be back to having what you have now while still allowing other projects to subrepo.

2018-04-12 19:11 UTC, romainf-unity requested changes
Minor change to fix in the README, but I'll approve this PR (it is in line with the structure imposed by the package manager)

2018-04-12 19:11 UTC, romainf-unity commented on README.md
> +- Run `git clone https://github.com/Unity-Technologies/graph-visualizer` **(Note HTTPS)**
I don't think it's needed now to precise "https", it's fairly common now, and users will copy/paste the line anyway.

2018-04-12 19:16 UTC, amirebrahimi commented
Should be good now

2018-04-12 19:44 UTC, romainf-unity approved these changes

2018-04-12 19:44 UTC, merged